CREATE OR REPLACE VIEW PERSON_REGION_REPORT_V 
AS

SELECT
    PERSON.FULL_NAME,
    NOC_REGION.REGION_NAME
FROM 
    PERSON
    JOIN PERSON_REGION ON PERSON.ID = PERSON_REGION.PERSON_ID
    JOIN NOC_REGION ON PERSON_REGION.REGION_ID = NOC_REGION.ID
/

SELECT * FROM PERSON_REGION_REPORT_V FETCH FIRST 10 ROWS ONLY;
